nav_wp:
  ros__parameters:
    waypoints: ["wp1", "wp2", "wp3", "wp4", "wp5", wp8", "wp7", "wp8"]
    wp1: [3.9, 0.383]
    wp2: [2.64, 6.3]
    wp3: [3.13, 12.3]
    wp4: [0.252, 14.2]
    wp5: [-4.13, 11]
    wp6: [-5.08, 3.55]
    wp7: [-5.85, -9.53]
    wp8: [3.4, -9.84]
